apiVersion: v1
kind: Pod
metadata:
  name: api-worker
spec:
  containers:
  - name: web-api
    image: nginx:alpine
  affinity:
    podAffinity:
      # SOFT POD AFFINITY: Prefer to be close to the database
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - database # Looks for the label we gave the DB pod
          topologyKey: kubernetes.io/hostname # Prefers the exact same machine
