apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  labels:
    disk: ssd
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["/bin/sh","-c"]
      args:
        - |
          echo "pod-affinty pod scheduled";sleep 3000

  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - sky
          topologyKey: kubernetes.io/hostname
