apiVersion : v1
kind : Pod
metadata :
  name : new-pod
  namespace : cw-ns
spec :
  containers :
    - name : my-cont
      image : nginx
      envFrom:
        - configMapRef :
              name : conf


