apiVersion : v1
kind : Pod
metadata :
  name : my-pod-configmap
  namespace : cw-ns
spec :
  containers :
    - name : my-cont
      image : nginx
      command : ["/bin/sh","-c"]
      args :
        - echo "username = $cw"; sleep 3600

# kubectl create cm my-config -n cw-ns --from-literal=username=mac_admin
      env :
        - name : cw
          valueFrom :
            configMapKeyRef :
              name : my-config
              key : username
