apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - prod
      containers:
      - name: python-alpine
        image: python:3.12-alpine
        command: ["sleep", "infinity"] # Keeps pod running
        volumeMounts:
        - name: script-vol
          mountPath: /app
      volumes:
      - name: script-vol
        configMap:
          name: ping-script-config
