apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: demo-nginx
spec:
  replicas: 2 # Spins up exactly 2 pods
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
spec:
  type: ClusterIP # Keeps the service internal to the cluster virtual network
  ports:
  - port: 80        # The port exposed on the service IP
    targetPort: 80  # The port it looks for inside the nginx containers
  selector:
    tier: frontend  # Matches the label assigned to our deployment pods

