apiVersion: v1
kind: Pod
metadata:
  name: security
spec:
  # Pod-level security context
  securityContext:
    runAsUser: 3500
    runAsGroup: 4500
    fsGroup: 2000

  containers:
  - name: shell
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 10000"
    # Container-level security context
    securityContext:
      runAsUser: 1500 # Perfectly overrides 3500 for this specific container
# privileged: true tells Kubernetes to give the container root-level access to the host's kernel and devices.
